### ISSUE TITLE
Can't add Good

### ISSUE THREAD

**Issue by mgralikowski** [dbojdo/wFirma#26]
Niestety użycie metody createFromBrutto() generuje błąd:

_Maksymalna liczba cyfr w części ułamkowej to 2._ dla wartości netto.

np. dla kwoty 100zł. Widocznie wFirma nie chce niedomówień i przyjmują tylko float o określonej precyzji.

**Comment by mgralikowski** [comment]
Ponad idąc dalej, nie jestem w stanie dodać produktu, ponieważ otrzymuje błąd:

```
          0 => Webit\WFirmaSDK\Entity\Error {#5230 ▼
            -field: "vat_code_id"
            -message: "Nieprawidłowa stawka."
            -method: Webit\WFirmaSDK\Entity\ErrorMethod {#5247 ▼
              -name: "1"
            }
          }
          1 => Webit\WFirmaSDK\Entity\Error {#5250 ▼
            -field: "netto"
            -message: "Maksymalna liczba cyfr w części ułamkowej to 2."
            -method: null
          }
          2 => Webit\WFirmaSDK\Entity\Error {#5239 ▼
            -field: "vat_code_purchase_id"
            -message: "Pole przyjmuje tylko wartości dodatnie."
            -method: null
          }
```

Próbuje dodać stawkę "zwolniony", które ma ID `233`. Po niskiej wartości identyfikatora strzelam, że te wartości są dla wszystkich kont zbieżne.

**Comment by dbojdo** [comment]
Naprawione w https://github.com/dbojdo/wFirma/pull/31
