### ISSUE TITLE
Contractor tags

### ISSUE THREAD

**Issue by mgralikowski** [dbojdo/wFirma#34]
Przekazuje taki parametr do obiektu Contract:
`tags: new TagIds([new TagId(180294)]),`

niestety w ostatecznym json gałąź wygląda tak:

`<tags/>` (jest pusta).

**Comment by tryllu** [comment]
Daniel, mam podobną potrzebę j/w. 
Moim zdaniem gdzieś w konstrukcji dla Serializera jest błąd, ale nie biegłości aby to naprawić.
Możesz pomóc?
