### ISSUE TITLE
Upgrade from Basic Auth to OAuth 1.0a

### ISSUE THREAD

**Issue by Qrzysio** [dbojdo/wFirma#37]
Any plans to upgrade to OAuth 1.0a?

> Informujemy, że wraz z końcem czerwca 2023 roku metoda Basic połączenia się z API zostanie wyłączona. Ta zmiana może wpłynąć na działanie niektórych integracji z systemem wFirma, dlatego zachęcamy do kontaktu z ich twórcami w celu aktualizacji integracji.

> Please be advised that the Basic method of connecting to the API will be deactivated at the end of June 2023. This change may affect the performance of some wFirma integrations, so we encourage you to contact their developers to update your integration.

**Comment by mgralikowski** [comment]
Rozmawiałem z wFirmą i ma być dodana jeszcze dodana 3 forma autoryzacji - token aplikacyjny, prawdopodobnie będzie bardziej przystępny jeżeli chodzi o migracje z basic auth.

**Comment by Qrzysio** [comment]
Świetna wiadomość!

**Comment by dbojdo** [comment]
> Rozmawiałem z wFirmą i ma być dodana jeszcze dodana 3 forma autoryzacji - token aplikacyjny, prawdopodobnie będzie bardziej przystępny jeżeli chodzi o migracje z basic auth.

Super, dzięki za info!

**Comment by karolzlot** [comment]
@mgralikowski z ciekawości jak z nimi rozmawiałeś, mailem się udało?

**Comment by mgralikowski** [comment]
Po prostu odpowiedziałem na ich komunikat, reply-to jest na adres `pomoc@wfirma.pl`, który mi wyglądał na legitny, więc spróbowałem, ale generalnie gdyby to nie zadziałało zawsze jest wewnętrzny system wiadomości, gdzie nie zostałem nigdy bez odpowiedzi.

**Comment by jacekkow** [comment]
Pojawiła się dokumentacja API key: https://doc.wfirma.pl/#autoryzacja

Prócz accessKey i secretKey potrzeba jeszcze "appKey - dostarczane przez wfirma.pl indywidualnie dla każdej aplikacji".

Poza tym wystarczy dodawać trzy nagłówki do każdego żądania.

**Comment by dbojdo** [comment]
@jacekkow Hej! Dzięki za info. Wrzuciłem wsparcie dla API Keys (udokumentowane w README). Póki co nie mam skonfigurowanych API Keys, więc jeśli ktoś w Was mógłby sprawdzić czy to faktycznie działa (branch feature/issue-37-api-auth), to będę wdzięczny.

**Comment by jacekkow** [comment]
Aktualizacja wprowadzająca API Keys będzie dostępna dopiero 5 lutego ;)
https://wfirma.pl/blog/-aktualizacja-systemu-luty-2023

**Comment by dbojdo** [comment]
Czyli jesteśmy do przodu!

**Comment by velPL** [comment]
Sprawdziłem działanie na swoim zestawie kluczy API.  Wydaje się działać, ale wymaga dwóch zmian w `Webit\WFirmaSDK\Entity\EntityApiFactory`, bo teraz jest ścisłe dependency klasy ` Webit\WFirmaSDK\Auth\BasicAuth`:

1. Linia 5 powinna być: `use Webit\WFirmaSDK\Auth\Auth;`
2. Linia 23 type-hitt argumentu $auth powinien być `Auth`

**Comment by dbojdo** [comment]
> Sprawdziłem działanie na swoim zestawie kluczy API. Wydaje się działać, ale wymaga dwóch zmian w `Webit\WFirmaSDK\Entity\EntityApiFactory`, bo teraz jest ścisłe dependency klasy ` Webit\WFirmaSDK\Auth\BasicAuth`:
> 
> 1. Linia 5 powinna być: `use Webit\WFirmaSDK\Auth\Auth;`
> 2. Linia 23 type-hitt argumentu $auth powinien być `Auth`

Dzięki! Poprawiłem.

**Comment by slav123** [comment]
mamy gdzieś przykład jak teraz się autoryzowac mając te 3 zmienne?

```
--header 'accessKey: ********************************' \
--header 'secretKey: ********************************' \
--header 'appKey: ********************************' \
```

te zmiany sa poprawione w kodzie?

**Comment by dbojdo** [comment]
Zmiany są branchu `feature/issue-37-api-auth`, możesz spróbować go użyć, aby sprawdzić czy działa. Ja jeszcze nie miałem możliwości tego przetestować.

**Comment by mgralikowski** [comment]
Aktywność wzrosła w ostatnich w 48h istnienia starej metody :) (jakby ktoś nie wiedział - w tym tygodniu trzeba przemigrować).

**Comment by dbojdo** [comment]
@mgralikowski czy ta zmiana z brancha działa poprawnie?

**Comment by slav123** [comment]
u mnie dziala, mozna jechac na branchu bez problemu. wszystko dziala jak przy basic auth.

**Comment by mgralikowski** [comment]
Sorki za późną odpowiedź, niestety utworzenie integracji wymaga kontaktu z supportem via e-mail celem uzyskania app key, więc musiałem czekać na klucze. Te klucze mają tylko znaczenie informacyjne (ich logi wewnętrzne).

Tak, również potwierdzam, że wszystko działa. Dzięki za update!

**Comment by Qrzysio** [comment]
Potwierdzam, działa.
