### ISSUE TITLE
Dependency abandoned - fzaninotto/faker 

### ISSUE THREAD

**Issue by pperzyna** [dbojdo/wFirma#8]
```
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by dbojdo** [comment]
Abandon może oznaczać tylko tyle, że autor nie rozwija aktywnie już tej biblioteki. Póki co nie znalazłem dobrej alternatywy dla tego pakietu. Jest on zresztą tylko dependencją deweloperską, używaną w testach. Instalacja w innym projekcie nie wymaga instalacji  fzaninotto/faker. Jednak warto mieć na uwadze, że będzie trzeba przepisać testy, jeśli projekt zostanie całkowicie usunięty. Można też pomyśleć o zrobieni własnego forka.

**Comment by dbojdo** [comment]
Naprawione w https://github.com/dbojdo/wFirma/pull/31
